name: SonarQube-Cloud 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: 'npm'

      - name: Start MongoDB 8.0
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: '8.0'

      - name: Install dependencies 
        run: npm ci 

      - name: Generate coverage info
        run: npm run coverage 

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
